version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: giftcards
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  app:
    build: .
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/giftcards?schema=public
      NODE_ENV: development 
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network
    command: >
      sh -c "until pg_isready -h db -p 5432; do sleep 1; done
      && npx prisma migrate deploy
      && node dist/index.js"

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: